(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: texecom-power-reset.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Saturday, 26 September 2026 at 14:57)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.8)
(Tool: 2 -> Dia: 0.8)
(Tool: 3 -> Dia: 0.8)
(Tool: 4 -> Dia: 0.8)
(Tool: 5 -> Dia: 0.9)
(Tool: 6 -> Dia: 1.0)
(Tool: 7 -> Dia: 1.3)
(Tool: 8 -> Dia: 1.5)
(Tool: 9 -> Dia: 3.2)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 60.0)
(Tool: 2 -> Feedrate: 60.0)
(Tool: 3 -> Feedrate: 60.0)
(Tool: 4 -> Feedrate: 60.0)
(Tool: 5 -> Feedrate: 60.0)
(Tool: 6 -> Feedrate: 60.0)
(Tool: 7 -> Feedrate: 60.0)
(Tool: 8 -> Feedrate: 60.0)
(Tool: 9 -> Feedrate: 60.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)
(Tool: 5 -> Feedrate Rapids: 1500)
(Tool: 6 -> Feedrate Rapids: 1500)
(Tool: 7 -> Feedrate Rapids: 1500)
(Tool: 8 -> Feedrate Rapids: 1500)
(Tool: 9 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -2.0)
(Tool: 2 -> Z_Cut: -2.0)
(Tool: 3 -> Z_Cut: -2.0)
(Tool: 4 -> Z_Cut: -2.0)
(Tool: 5 -> Z_Cut: -2.0)
(Tool: 6 -> Z_Cut: -2.0)
(Tool: 7 -> Z_Cut: -2.0)
(Tool: 8 -> Z_Cut: -2.0)
(Tool: 9 -> Z_Cut: -2.0)

(Tools Offset: )
(Tool: 5 -> Offset Z: 0.0)
(Tool: 6 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2.0)
(Tool: 2 -> Z_Move: 2.0)
(Tool: 3 -> Z_Move: 2.0)
(Tool: 4 -> Z_Move: 2.0)
(Tool: 5 -> Z_Move: 2.0)
(Tool: 6 -> Z_Move: 2.0)
(Tool: 7 -> Z_Move: 2.0)
(Tool: 8 -> Z_Move: 2.0)
(Tool: 9 -> Z_Move: 2.0)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: 0.0000, 0.0000 mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    2.4500 ...   89.4400  mm)
(Y range:    2.4500 ...   68.6500  mm)

(Spindle Speed: 12000 RPM)
G21
G90
G94

G01 F60.00

M5
G00 Z15.0000
T5
G00 X0.0000 Y0.0000                
M6
(MSG, Change to Tool Dia = 0.9000 ||| Total drills for tool T5 = 34)
M0
G00 Z15.0000

G01 F60.00
M03 S12000
G00 X22.0500 Y36.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X24.5900 Y36.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X71.1600 Y66.6700
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X73.7000 Y66.6700
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X76.2400 Y66.6700
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X78.7800 Y66.6700
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X81.3200 Y66.6700
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X83.8600 Y66.6700
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X86.4000 Y66.6700
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X88.9400 Y66.6700
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X88.9400 Y51.4300
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X86.4000 Y51.4300
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X83.8600 Y51.4300
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X81.3200 Y51.4300
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X78.7800 Y51.4300
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X76.2400 Y51.4300
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X73.7000 Y51.4300
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X71.1600 Y51.4300
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X50.5900 Y36.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X48.0500 Y36.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X44.7000 Y30.1000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X51.0500 Y29.7100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X61.0500 Y22.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X63.5900 Y22.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X66.1300 Y22.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X68.6700 Y22.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X71.2100 Y9.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X61.0500 Y9.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X51.0500 Y19.5500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X44.7000 Y18.1000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X25.0500 Y19.5500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X18.7000 Y18.1000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X18.7000 Y30.1000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X25.0500 Y29.7100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00
G00 X0.0 Y0.0


