(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: texecom-power-reset.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Saturday, 26 September 2026 at 14:58)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.8)
(Tool: 2 -> Dia: 0.8)
(Tool: 3 -> Dia: 0.8)
(Tool: 4 -> Dia: 0.8)
(Tool: 5 -> Dia: 0.9)
(Tool: 6 -> Dia: 1.0)
(Tool: 7 -> Dia: 1.3)
(Tool: 8 -> Dia: 1.5)
(Tool: 9 -> Dia: 3.2)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 60.0)
(Tool: 2 -> Feedrate: 60.0)
(Tool: 3 -> Feedrate: 60.0)
(Tool: 4 -> Feedrate: 60.0)
(Tool: 5 -> Feedrate: 60.0)
(Tool: 6 -> Feedrate: 60.0)
(Tool: 7 -> Feedrate: 60.0)
(Tool: 8 -> Feedrate: 60.0)
(Tool: 9 -> Feedrate: 60.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)
(Tool: 5 -> Feedrate Rapids: 1500)
(Tool: 6 -> Feedrate Rapids: 1500)
(Tool: 7 -> Feedrate Rapids: 1500)
(Tool: 8 -> Feedrate Rapids: 1500)
(Tool: 9 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -2.0)
(Tool: 2 -> Z_Cut: -2.0)
(Tool: 3 -> Z_Cut: -2.0)
(Tool: 4 -> Z_Cut: -2.0)
(Tool: 5 -> Z_Cut: -2.0)
(Tool: 6 -> Z_Cut: -2.0)
(Tool: 7 -> Z_Cut: -2.0)
(Tool: 8 -> Z_Cut: -2.0)
(Tool: 9 -> Z_Cut: -2.0)

(Tools Offset: )
(Tool: 9 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2.0)
(Tool: 2 -> Z_Move: 2.0)
(Tool: 3 -> Z_Move: 2.0)
(Tool: 4 -> Z_Move: 2.0)
(Tool: 5 -> Z_Move: 2.0)
(Tool: 6 -> Z_Move: 2.0)
(Tool: 7 -> Z_Move: 2.0)
(Tool: 8 -> Z_Move: 2.0)
(Tool: 9 -> Z_Move: 2.0)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: 0.0000, 0.0000 mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    2.4500 ...   89.4400  mm)
(Y range:    2.4500 ...   68.6500  mm)

(Spindle Speed: 12000 RPM)
G21
G90
G94

G01 F60.00

M5
G00 Z15.0000
T9
G00 X0.0000 Y0.0000                
M6
(MSG, Change to Tool Dia = 3.2000 ||| Total drills for tool T9 = 2)
M0
G00 Z15.0000

G01 F60.00
M03 S12000
G00 X4.0500 Y66.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X86.0500 Y4.0500
G01 Z-2.0000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00
G00 X0.0 Y0.0


